spring:
  rabbitmq: #rabbitmq相关配置
    host: localhost
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis:
  typeAliasesPackage: com.macro.mall
  mapper-locations:
    - classpath*:com/**/xmlmapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /system/login
      - /system/register
      - /system/user/info/*
      - /admin/logout
      - /minio/upload
    
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true
ribbon:
  eureka:
    enabled: true
logging:
  level: #修改日志级别
    com.macro.cloud.service.UserService: debug


security:
  oauth2:
    client:
      client-id: mall
      client-secret: admin123
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: http://mall-auth/oauth/check_token
